AWSTemplateFormatVersion: 2010-09-09
Description: >-
  email-sender

Transform:
- AWS::Serverless-2016-10-31
Resources:
  
  SendEmailRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: sendemail-api
      BinaryMediaTypes:
        - multipart~1form-data
      Auth:
        ApiKeyRequired: true
  
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: SendEmailApiKey
      Enabled: true

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties: 
      ApiStages: 
        - ApiId: !Ref SendEmailRestApi
          Stage: !Ref SendEmailRestApiProdStage

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  SendEmailDependenciesLayers:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nodejs-mailer-dependencies
      Description: node modules with all dependencies to send email
      ContentUri: "./layers"
      CompatibleRuntimes:
        - nodejs18.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs18.x

  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sendEmail
      CodeUri: "./build"
      Handler: index.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Layers:
        - !Ref SendEmailDependenciesLayers
      Timeout: 100
      Description: A simple Lambda function to send a email throught AWS SES
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - "ses:SendEmail"
                - "ses:SendRawEmail"
              Resource: "*"
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref SendEmailRestApi
            Path: /
            Method: POST
            Auth: 
              ApiKeyRequired: true

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${SendEmailRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"